version: '3.6'

services:
  postgres:
    image: postgres:15.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
  pg-admin:
    image: dpage/pgadmin4:latest
    restart: always
    user: root
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@localhost.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - 8080:80
    volumes:
      - ./data/pgadmin-data:/var/lib/pgadmin

networks:
  default:
    name: triangle-network
    external: true